### ISSUE TITLE
IndexOutofRange Exception

### ISSUE THREAD

**Issue by MiroTheSuperDev** [BayatGames/Support#11]
I imported SaveGamePro latest version on a clean project that I just started and got this 

`ystem.IndexOutOfRangeException: Array index is out of range.
  at BayatGames.SaveGamePro.Editor.SaveGameTypeCreator.UpdateTypeManager () [0x0000c] in D:\Work Games\Bouncy\Bouncy\Assets\BayatGames\SaveGamePro\Editor\SaveGameTypeCreator.cs:630 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222 `

**Comment by MiroTheSuperDev** [comment]
This is the first asset I just imported and that's the error 


Unity version 2018.2.18f1

**Comment by hasanbayatme** [comment]
Hello.
Thanks for your report, I appreciate it.
I've fixed it and this bug fix will be available in the next update.
Also, this issue is not something important or critical, it is just a script execution issue.

Thanks!

**Comment by MiroTheSuperDev** [comment]
I'm glad that you have noticed the issue and fixed it that fast .

Thank you for your great support.

**Comment by MiroTheSuperDev** [comment]
@EmpireWorld Why the update did not come out yet ??

If you want to wait to add new features first, then can you tell me how to fix it so I can do it my self

I really need to finish my game development and I want to make sure the game won't have bugs on such a simple issue

**Comment by hasanbayatme** [comment]
@Supermiro19 Oh sorry really, I've been working on Encryption recently for Save Game Pro, it is almost done, just drop me an Email over hasanbayat1393@gmail.com, and then I'll send you the updated version immediately.
Also, this bug is not critical, it won't affect anything at all, it is an effectless bug.

Thanks for the patience and sorry for the delay! (I just didn't release the update immediately as this bug is nothing at all, it is just an error happens at some random points, and it won't affect anything, also this error is editor-only)

**Comment by hasanbayatme** [comment]
@Supermiro19 The new version has been submitted for Review, so if you want to get it instantly, just drop e an email at hasanbayat1393@gmail.com, then I'll attach the latest version of Save Game Pro.

Thanks, Good luck!
