### ISSUE TITLE
Save game pro question

### ISSUE THREAD

**Issue by rlee1990** [BayatGames/Support#15]
Is this compatible with Gamesparks?

**Comment by hasanbayatme** [comment]
Hi.

Thanks for your interest.
No, it isn't currently, but it is planned for the next updates.
Anyway, if you're actively looking for that, you can also develop it on your side easily.
Just take a look at existing integrations like PlayFab, Web and other examples which will help you on how to make integration, otherwise, you need to wait for the next updates.

Also, I'm currently or actively working on a new save system which will include all integrations possible, and after the release of this product, Save Game Pro will go on Maintenance mode and won't receive feature updates, and will keep receiving bug fixes and minor improvements.

- [Trello - Save Game Pro card:](https://trello.com/c/SgYpFsfd)
- [Trello - Bayat Save Game card](https://trello.com/c/3do9VuyF)

I would be happy to hear your comments.

Hope this helps.
Thanks.

**Comment by rlee1990** [comment]
Okay thanks do you happen to have a time frame? Just asking because i have a game that is live with gamesparks. But the game saves that i push up somehow are empty. Could i replace the playfabs with gamesparks?

**Comment by hasanbayatme** [comment]
Hi again, sorry for the late reply.
Yeah, you can take a look at PlayFab integration and build the GameSparks integration on top of that, but it requires a bit of programming knowledge.

So, if it is required for you to be added as soon as possible or you need a custom integration for GameSparks, I can build it, my rate is $60/h and it is roughly 4 hours of work, I can agree with $200, but it all depends on your choice.

Thanks.

**Comment by rlee1990** [comment]
Thanks for the offer but I did speak with the Playfab team and they will work with me to increase limits for what I need. So I went back to Playfab and brought the Save Game Pro already.

**Comment by hasanbayatme** [comment]
Great, thanks for the update <3
I wish the best of luck.
Let me know if you had any questions.
